### ISSUE TITLE
Compiler Breaks Blade Extensions

### ISSUE THREAD

**Issue by jakecarlson** [fitztrev/laravel-html-minify#21]
The minifier seems to ignore custom Blade extensions that are added via Blade::extend. The extension is successfully added to the BladeCompiler::extensions array, but when the BladeCompiler::compileExtensions() is run, those extensions are no longer in the extensions array.

**Comment by fitztrev** [comment]
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)

**Comment by Rolice** [comment]
I have designed a solution, without changing the package files themselves. I have left the resolver ID `blade.php` and I have written custom Facade to resolve the `LaravelHtmlMinifyCompiler`.

``` php
<?php
use \Illuminate\Support\Facades\Facade;

/**
 * @see \Illuminate\View\Compilers\BladeCompiler
 */
class LaravelHtmlMinifyFacade extends Facade {

    /**
     * Get the registered name of the component.
     *
     * @return string
     */
    protected static function getFacadeAccessor()
    {
        return static::$app['view']->getEngineResolver()->resolve('blade.php')->getCompiler();
    }

}
```

With this facade I can easily do the extending like with Blade:

``` php
LaravelHtmlMinifyFacade::extend(function ($view, $compiler) {
    $pattern = $compiler->createPlainMatcher('continue');
    return preg_replace($pattern, '<?php continue; ?>', $view);
});
```

If you create alias of `LaravelHtmlMinifyFacade` in app config, you can even call it like: `LaravelHtmlMinify::extend`.

The solution is also made on patch by forking the master branch. This way the issue will be resolved inside the package itself.
