### ISSUE TITLE
Do not resolve view in provider's register() method.

### ISSUE THREAD

**Issue by franzliedke** [fitztrev/laravel-html-minify#38]
You currently [extend the view](https://github.com/fitztrev/laravel-html-minify/blob/8005fc4a8489ca0fc44dbf2514e35148eb3a8693/src/Fitztrev/LaravelHtmlMinify/LaravelHtmlMinifyServiceProvider.php#L25-47) directly in the `register()` method. This should never be done at this point, because it may cause conflicts with other packages.

Either move this code to the `boot()` method, or - my preferred method, as the code will only be run when needed - wrap it in something like this:

    $app->resolving('view', function($view) {
        // your stuff here...
    });

**Comment by fitztrev** [comment]
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)
