### ISSUE TITLE
IE conditional comments issue in IE 7

### ISSUE THREAD

**Issue by PaddyHu** [fitztrev/laravel-html-minify#41]
In internet explorer 7 minified conditional comment doesn't works after minfiying ( in IE8 it's not problem).
I had to put it in a different file with {{-- skipmin --}} and it solved the problem, but it would be great if script leave line breaks at ie conditional comment parts.

Thanks!

**Comment by fitztrev** [comment]
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)
