### ISSUE TITLE
Config Settings

### ISSUE THREAD

**Issue by robertccs** [fitztrev/laravel-html-minify#47]
I'd like to check if it's feasable to have a setting in the config file to compress files containing JS as well.

**Comment by fitztrev** [comment]
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)

**Comment by fitztrev** [comment]
In the html-minifier js settings, you can specify to minify files including js.
