### ISSUE TITLE
Laravel 5 Version Please ???

### ISSUE THREAD

**Issue by courtaks** [fitztrev/laravel-html-minify#49]
Please need an update for Laravel 5 version... 
waiting for this update... 
thanks !

**Comment by GrahamCampbell** [comment]
@courtaks I maintain a L5 version if you're interested.

NB. I'm deleting this comment from github after posting so that you get an email, but nobody else sees the comment as not to piss off @fitztrev.

**Comment by dhardtke** [comment]
see #48

**Comment by fitztrev** [comment]
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)
