### ISSUE TITLE
Laravel HTML Minify no longer works for unknown reasons

### ISSUE THREAD

**Issue by ziming** [fitztrev/laravel-html-minify#50]
Hi,

I'm not exactly sure why but since recently, my views files no longer gets minified, even if I edit and save them. or run find . -name "*.blade.php" -exec touch {} \;

So I'm asking here to see if there are any other ways I could do to get it working for me again.

**Comment by ziming** [comment]
I'm using laravel 4.2

**Comment by kevindperezm** [comment]
Same issue here. Same laravel version. Maybe a regression?

**Comment by razvaniacob** [comment]
I have the same issue! laravel 4.2.8 Any thoughts?

**Comment by fitztrev** [comment]
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)

**Comment by infinityfarm** [comment]
wow nice resolution there
