### ISSUE TITLE
blade tags in config not working

### ISSUE THREAD

**Issue by ITwrx** [fitztrev/laravel-html-minify#53]
i have 
Blade::setEscapedContentTags('{{', '}}');
Blade::setContentTags('{!!', '!!}');
set in my routes.php which works fine (l5 came out while i was in the middle of my 4.2 app so i did this to lessen the pain of migration later).

so i've set the same in laravel-html-minify/src/config but the {!! !!} tags are still being escaped.

Thanks

update: i'm not sure if the config file is being read, as enabled: true/false doesn't seem to be respected.

**Comment by fitztrev** [comment]
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)
