### ISSUE TITLE
Regarding your notice

### ISSUE THREAD

**Issue by dhardtke** [fitztrev/laravel-html-minify#54]
Hi,

you recently started recommending "gulp-htmlmin" and a custom gulpfile.js for minifying Laravel's compiled views, but it's not working well...

```
[21:44:22] Starting 'compress'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Parse Error: <li<?php echo Request::is("ucp") || Request::is("/") ? ' class="active"' : ''; ?>>
```

I just wanted to tell you and other people that htmlmin is not always a solution, at least not in my case where I have Blade tags inside the HTML, like

``` html
<li{{ Request::is("/") ? ' class="active"' : ""}}>
```

**Comment by baribadamshin** [comment]
I'm disappointed. Minification really doesn't work with php into html attributes

**Comment by xavadu** [comment]
Hello,

It isn't a suitable solution in most of the cases, when you work in your project and later you upload it to a git repository, the `storage` folder isn't uploaded, and usually you run the javascript task on the deployment process, not later to visit your page to generate the cache views.

It will be a bad practice to upload the content of your `storage` folder, and also can happen that not all the view of your site are cached, or maybe the cache get updated with a new file.

**Comment by fitztrev** [comment]
@xavadu I have a command I wrote that recompiles all the blade templates without having to visit/load the page. It uses `Blade::compile($file);` and you can just write a loop that passes in all your templates files (`File::allFiles(base_path().'/resources/views/')`).

IMO, the Gulp task is a much better approach than using the PHP package. I've been using it for the past 6 months or so.

**Comment by acacha** [comment]
What about first comment of @dhardtke? I have a lot of parse errors too so anybody have a solution?
