### ISSUE TITLE
Error with Gulp html compress

### ISSUE THREAD

**Issue by sakanaproductions** [fitztrev/laravel-html-minify#59]
I'm getting the following error when running the gulp compress from your wiki:

[21:03:45] Starting 'compress'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: <a class="btn btn-primary navbar-btn" <?php echo e($modelItem->isCreatable() ? '' : 'disabled'); ?> href="<?php echo e($newEntryRoute); ?>"><i class="fa fa-plus"></i> <?php echo e(Lang::get('admin::lang.table.new-entry')); ?></a>
            <div class="table-responsive">
                <table class="table table-striped table-hover" id="dataTable" <?php echo $modelItem->renderTableAttributes(); ?>>
                    <thead>
                        <tr>
                            <?php foreach($columns as $column): ?>
                                <?php echo $column->renderHeader(); ?>

```
                        <?php endforeach; ?>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($rows as $row): ?>
                        <tr>
                            <?php foreach($columns as $column): ?>
                                <?php echo $column->render($row, count($rows)); ?>

                            <?php endforeach; ?>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
                <?php if($modelItem->isColumnFilter() && ! $modelItem->isAsync()): ?>
                    <tfoot>
                        <tr>
                            <?php foreach($columns as $column): ?>
                                <td></td>
                            <?php endforeach; ?>
                        </tr>
                    </tfoot>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>
```

<?php $__env->stopSection(); ?>
<?php echo $__env->make('admin::_layout.inner', array_except(get_defined_vars(), array('__data', '__path')))->render(); ?>

**Comment by grimmdude** [comment]
I had the same issue; it's because of the nested PHP tags within the HTML tags.  I opened this issue in the  kangax/html-minifier repo and they updated it to include an option for `ignoreCustomFragments`.

https://github.com/kangax/html-minifier/issues/421

-Garrett

**Comment by grimmdude** [comment]
I updated the wiki in this repo to reflect this fix (hope owner doesn't mind).  Also, be sure to update to the latest version of `html-minifier`.

-Garrett

**Comment by grimmdude** [comment]
Scratch that wiki update, just noticed the latest `html-minifier` ignores those custom fragments by default.

-G

**Comment by sakanaproductions** [comment]
@grimmdude okay, updated html-minifier and now getting this:

`events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: <a
                {...this.props}
                href="javascript:;"
                role="button"
                className={(this.props.className || '') + ' btn'}
                data-keyboard="true"
            />
        );
    }
});
`

**Comment by grimmdude** [comment]
I think the issue is with those embedded quotes in the `className` attribute.  You'll need to write a regEx to ignore those `{}` blocks and use is in the `ignoreCustomFragments` option.  Check this comment: https://github.com/kangax/html-minifier/issues/421#issuecomment-150911891

**Comment by sakanaproductions** [comment]
awesome, got it... i wasn't using Regex for `ignoreCustomFragments`... thanks again.
