### ISSUE TITLE
Bigger wins by removing other things than whiitespace.

### ISSUE THREAD

**Issue by richbradshaw** [fitztrev/laravel-html-minify#8]
I've been using code like this:

    $to_cache = str_replace(array("</option>","</td>","</tr>","</th>","</dt>","</dd>","</li>","</body>","</html>"),"",$to_cache);
    $to_cache = preg_replace('/(href|src|id|class|name|type|rel|sizes|lang|title|itemtype|itemprop)=(\"|\')([^\"\'\`=<>\s]+)(\"|\')/i', '$1=$3', $to_cache);

in production for a long time – specifically dropping all the optional end tags that don't make a difference anyway (code still validates without them), and removing quotes round values that don't need quoting – e.g. `<div class='test'>` can be written as `<div class=test>` without any change in functionality. If it has a space then I don't do that.

This reduces the size by a relatively large amount.

**Comment by fitztrev** [comment]
Now using gulp to compress :)

Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)
